# -*- coding: utf-8 -*-
"""11_June_loading_model_Animal_classification.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/100xdAiJq9CLjQHPd8Exq-9M3JFmQr1yL
"""

import numpy as np
from tensorflow.keras.utils import load_img,img_to_array
import tensorflow as tf

model = tf.keras.models.load_model('Multi_Animal_class.h5')

model.summary()

class_names = ['Bear', 'Bird', 'Cat', 'Cow', 'Deer', 'Dog', 'Dolphin', 'Elephant', 'Giraffe', 'Horse', 'Kangaroo', 'Lion', 'Panda', 'Tiger', 'Zebra']

class_names

img

img_arr = img_to_array(img)

img_arr

img_arr.shape

img_arr = img_arr.reshape(1,160,160,3)

img_arr.shape

model.predict(img_arr)

model.predict(img_arr).round()

np.argmax(model.predict(img_arr).round())

class_names[np.argmax(model.predict(img_arr).round())]

