# -*- coding: utf-8 -*-
"""11_june_animal_classification.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sOMZ0J7mDPXb_V3i9cQnc6JMAnd_HkUy
"""

import numpy as np
import matplotlib.pyplot as plt
import os
import tensorflow as tf

import kagglehub

# Download latest version
path = kagglehub.dataset_download("amankumar094/animal-dataset")

print("Path to dataset files:", path)

path

data_dir = os.path.join(os.path.dirname('C:\\Users\\rushi\\.cache\\kagglehub\\datasets\\amankumar094\\animal-dataset\\versions\\1\\dataset'), 'dataset')

data_dir

os.listdir(data_dir)

BATCH_SIZE = 32
IMG_SIZE = (160,160)

train_dataset = tf.keras.utils.image_dataset_from_directory(data_dir,
                                                            shuffle=True,
                                                            batch_size=BATCH_SIZE,
                                                            image_size=IMG_SIZE

                                                        )

train_dataset.class_names

validation_dataset = tf.keras.utils.image_dataset_from_directory(data_dir,
                                                                shuffle=True,
                                                                 batch_size=BATCH_SIZE,
                                                                 image_size=IMG_SIZE
                                                                )

validation_dataset.class_names

train_dataset.take(1)

for img,lb in train_dataset.take(1):
    print(img.shape)
    print(lb.shape)

for img,lb in train_dataset.take(1):
    print(img.shape)
    print(lb )

for img,lb in train_dataset.take(1):
    print(img)
    print(lb)

for img,lb in train_dataset.take(1):
    print(img[0])
    print(lb[0])

for img,lb in train_dataset.take(1):
    print(img[0].numpy())
    print(lb[0].numpy())

for img,lb in train_dataset.take(1):
    print(img[0].numpy().astype('uint8'))
    print('class of image \n')
    print(lb[0].numpy())

class_names = train_dataset.class_names

class_names

plt.figure(figsize=(10,10))
for images, labels in train_dataset.take(1):
    for i in range(9):
        ax = plt.subplot(3,3,i+1)
        plt.imshow(images[i].numpy().astype('uint8'))
        plt.title(class_names[labels[i]])
        plt.axis('off')

val_batches = tf.data.experimental.cardinality(validation_dataset)

val_batches

train_batches = tf.data.experimental.cardinality(train_dataset)

train_batches

test_dataset = train_dataset.take(val_batches // 5)
validation_dataset = train_dataset.skip(val_batches // 5)

print('number of validation batches: %d' % tf.data.experimental.cardinality(validation_dataset))
print('number of test batches:  %d' % tf.data.experimental.cardinality(test_dataset))

AUTOTUNE = tf.data.AUTOTUNE
train_dataset = train_dataset.prefetch(buffer_size=AUTOTUNE)
validation_dataset = validation_dataset.prefetch(buffer_size=AUTOTUNE)
test_dataset = test_dataset.prefetch(buffer_size=AUTOTUNE)

data_augmentation = tf.keras.Sequential([
    tf.keras.layers.RandomFlip('horizontal', input_shape=(160,160,3)),
    tf.keras.layers.RandomRotation(0.2)
])

for image,_ in train_dataset.take(1):
    plt.figure(figsize=(10,10))
    first_image = image[0]
    for i in range(9):
        ax = plt.subplot(3, 3, i + 1)
        augmented_image = data_augmentation(tf.expand_dims(first_image, 0))
        plt.imshow(augmented_image[0] / 255.0)
        plt.axis('off')

image_batch, label_batch = next(iter(train_dataset))
print(image_batch.shape)
print(label_batch.shape)

image_batch[0]

type(image_batch[0])

image_batch[0].numpy().astype('uint8')

plt.imshow(image_batch[0].numpy().astype('uint8'))
plt.show()

class_names[label_batch[0]]

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Rescaling,Dense,Conv2D,MaxPooling2D,Flatten
model = Sequential([
    data_augmentation,
    Rescaling(1./255),
    Conv2D(16, 3, padding='same', activation='relu'),
    MaxPooling2D(),
    Conv2D(32, 3, padding='same', activation='relu'),
    MaxPooling2D(),
    Conv2D(64, 3, padding='same', activation='relu'),
    MaxPooling2D(),

    Flatten(),
    Dense(128, activation='relu'),
    Dense(15, activation='softmax')
])

model.summary()

base_learning_rate = 0.0001
model.compile(
    optimizer = tf.keras.optimizers.Adam(learning_rate=base_learning_rate),
    loss = 'sparse_categorical_crossentropy',
    metrics = ['accuracy']
)

history = model.fit(train_dataset,epochs=50,validation_data=validation_dataset)

